### ISSUE TITLE
Answers are misplaced in Answers/Cisco_English_for_it_1.md Part 5 section 5.2.4

### ISSUE THREAD

**Issue by Noam-Alum** [ShayAviv/Cisco_English_For_IT#4]
In `Answers/Cisco_English_for_it_1.md` Part 5 section 5.2.4 the answers are not right, and the actual answer is in the question:

https://github.com/ShayAviv/Cisco_English_For_IT_Answers/blob/bbb1be2b6cfca75c961b994e64cd87ff7f9a4356/Answers/Cisco_English_for_it_1.md?plain=1#L544-L554

**For example:**
```text
| **2** | Person A: How detailed should our security policy be? Person B: It's supposedly meant to be extensive, but the last one was very brief. | The policy is supposedly meant to be extensive. |
```

The answer is: `The policy is supposedly meant to be extensive.`, but the actual answer is: `It's supposedly meant to be extensive, but the last one was very brief.`

**Comment by Noam-Alum** [comment]
@ShayAviv I'm pretty sure this is due to me using ChatGPT to format the answers to Markdown :see_no_evil:.

**Comment by ShayAviv** [comment]
Fixed, you are my savior @Noam-Alum 👯
