### ISSUE TITLE
Last answer in Answers/Appendix_B_-_Extra_Grammar_Exercises_part_one.md has part of the question.

### ISSUE THREAD

**Issue by Noam-Alum** [ShayAviv/Cisco_English_For_IT#5]
As you can see here:

https://github.com/ShayAviv/Cisco_English_For_IT_Answers/blob/bbb1be2b6cfca75c961b994e64cd87ff7f9a4356/Answers/Appendix_B_-_Extra_Grammar_Exercises_part_one.md?plain=1#L230

You need to remove **"To be honest, "** from the answer.

**Comment by ShayAviv** [comment]
Thanks for the notice
